### ISSUE TITLE
Makefile - Patching Issue: in-place editing only works for regular files

### ISSUE THREAD

**Issue by gitze** [freultwah/dovecot-xaps-daemon-freebsd#1]
===>  Patching for dovecot-xaps-daemon-g20210101
sed: /var/ports/root/dovecot-xaps-daemon-freebsd-master/work/dovecot-xaps-daemon-832de45/configs/xapsd/: in-place editing only works for regular files
*** Error code 1

```
OLD:  @${REINPLACE_CMD} -e 's|var\/run\/dovecot|var\/run\/xapsd|' ${WRKSRC}/configs/xapsd/

Fix:  @${REINPLACE_CMD} -e 's|var\/run\/dovecot|var\/run\/xapsd|' ${WRKSRC}/configs/xapsd/xapsd.yaml
```

**Comment by freultwah** [comment]
Oh, crap. That's what I get for editing on the phone. 👍 

It was fine, but then I really needed to get in there and remove two unnecessary lines, and apparently took 'xapsd.yaml' down as well. Thanks.
