### ISSUE TITLE
Proposal for modified rc-script

### ISSUE THREAD

**Issue by gitze** [freultwah/dovecot-xaps-daemon-freebsd#2]
I'm running on my server a very similar rc-startup script, but with different command options. Maybe you will incorporate this options.
Also I don't see a need to use the command "start_cmd".

```
#defaults
: ${xapsd_enable="NO"}
: ${xapsd_cmd="/usr/local/bin/xapsd"}
: ${xapsd_log="/var/log/xapsd.log"}
: ${xapsd_pidfile="/var/run/xapsd/xapsd.pid"}
#: ${xapsd_configpath="/usr/local/etc/xapsd"}
#: ${xapsd_configname="xapsd.yaml"}

#xapsd_args="-configPath ${xapsd_configpath} -configName ${xapsd_configname}"
xapsd_args=""

pidfile=${xapsd_pidfile}
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f -m 3 -o ${xapsd_log} ${xapsd_cmd} ${xapsd_args}"

run_rc_command "$1"
```

```
-P = PID to the daemon process, this will enable "-r" for automatic restart if the child process (xapsd) in case of error
-r = Supervise and restart the program after a one-second delay	if it has been terminated.
-f = Redirect daemon standard input, standard output and standard error to /dev/null
-m = Redirect output from the child process stdout (1), stderr (2), or both (3). This value specifies what is sent to syslog and the log file. The default is 3.
-o = Append output from the daemonized process to output_file. If the file does not exist, it is created with permissions 0600.
```

**Comment by freultwah** [comment]
Looks sane and nicer than mine, thanks. Using daemon's own facilities instead of piping the output madly is cool. I think I nicked it from somewhere. As far as I can remember, I was running the Perl version of xapsd and somebody had written an rc script for that. When it was time to switch, I just edited it a bit and did not think much, as long as it ran.

Are you very devoted to having the commented out lines included in the script?

**Comment by gitze** [comment]
No, the commented lines are leftovers from an implantation based on then "linux" code, where  configpath needed to be adopted to the FreeBSD env. I don't see the need anymore, as long as nobody would like to use a non standard config directory.

**Comment by freultwah** [comment]
Done.

**Comment by gitze** [comment]
Last remark: 
`${xapsd_args}` in `command_args` is now uninitialized. 
Maybe add : `${xapsd_args =""}` in the defaults section

**Comment by freultwah** [comment]
Yeah, I noticed its presence in command_args after I'd already committed. Mein Mistake.
